version: "3.8"

services:
  icarus-brain:
    image: ollama/ollama
    container_name: icarus-brain
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    env_file: .env
    environment:
      - OLLAMA_HOST=0.0.0.0
    entrypoint: [ "/bin/bash", "/entrypoint.sh" ]
    ports:
      - "8000:11434"
    networks:
      - icarus-net
    volumes:
      - ./ollama_data:/root/.ollama
      - ./ollama_entrypoint.sh:/entrypoint.sh:ro
      - ./Modelfile:/Modelfile:ro

  icarus-api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: icarus-api
    env_file: .env
    ports:
      - "8080:8000"
    networks:
      - icarus-net
    volumes:
      - ./backend:/app/backend:ro # Read-only source code mount for L1 restriction
      - ./workspace/ipc:/workspace/ipc
      - ./workspace/memory:/workspace/memory
      - ./workspace/projects:/workspace/projects
    depends_on:
      - icarus-brain

networks:
  icarus-net:
    driver: bridge
