"""
github_repo_producer.py — Periodic ingestion of a curated internship-listing
GitHub repo (speedyapply/2027-SWE-College-Jobs) into the job_scout pipeline.

The repo's README.md IS the "2027 USA SWE Internships" table (three
sections — FAANG+, Quant, Other — each delimited by
<!-- TABLE_*_START/END --> HTML comments), regenerated by the repo's own bot
several times a day. This polls it on an interval, parses new rows, and
dispatches each as a job_scout stub — same producer shape Phase 2 (digest
emails) uses, feeding the same tasks:job_scout stream worker_job_scout.py
already consumes.

This is NOT a generic markdown-table parser — it's written against this
specific repo's exact current structure (HTML-in-markdown cells: company
name+link in <a><strong>, a separate "Posting" cell whose <a href> is the
actual apply link, optional Salary column). A different curated-list repo
would need its own parser; deliberately not generalized further than the one
repo this was built against and verified live.
"""

import re
import hashlib
import logging
import asyncio

from .github_tools import github_read_file

logger = logging.getLogger(__name__)

REPO_OWNER = "speedyapply"
REPO_NAME = "2027-SWE-College-Jobs"
README_PATH = "README.md"

# The repo's own bot refreshes several times a day; polling faster than that
# just re-reads the same content.
POLL_INTERVAL_SECONDS = 6 * 3600

# The repo itself only keeps postings "within the last 120 days" (per its own
# README) before pruning them out — a TTL comfortably past that window means
# a posting that reappears after being briefly pruned/re-added is still
# treated as "already seen" rather than re-dispatched.
SEEN_KEY_TTL = 150 * 24 * 3600

# (section label, start marker, end marker) — verified against the live
# README as of the repo state this was built against.
_SECTION_MARKERS = [
    ("faang", "TABLE_FAANG_START", "TABLE_FAANG_END"),
    ("quant", "TABLE_QUANT_START", "TABLE_QUANT_END"),
    ("other", "TABLE_START", "TABLE_END"),
]

_STRONG_RE = re.compile(r"<strong>(.*?)</strong>", re.IGNORECASE | re.DOTALL)
_HREF_RE = re.compile(r'href="([^"]+)"', re.IGNORECASE)
_TAG_RE = re.compile(r"<[^>]+>")


def _strip_tags(text: str) -> str:
    return _TAG_RE.sub("", text).strip()


def _extract_section(readme: str, start_marker: str, end_marker: str) -> str:
    start = readme.find(f"<!-- {start_marker} -->")
    end = readme.find(f"<!-- {end_marker} -->")
    if start == -1 or end == -1 or end <= start:
        return ""
    return readme[start:end]


def _parse_table_rows(section: str) -> list[dict]:
    """Parse one section's markdown table into row dicts. Handles both the
    6-column (Company | Position | Location | Salary | Posting | Age) FAANG+/
    Quant layout and the 5-column (no Salary) Other layout."""
    rows = []
    for line in section.splitlines():
        line = line.strip()
        if not line.startswith("|") or not line.endswith("|"):
            continue
        cells = [c.strip() for c in line.strip("|").split("|")]
        if len(cells) < 5:
            continue
        # Skip the header row ("Company") and the "|---|---|..." separator row.
        if cells[0] in ("Company", "") or set(cells[0]) <= {"-", ":"}:
            continue

        company_match = _STRONG_RE.search(cells[0])
        if not company_match:
            continue
        company = _strip_tags(company_match.group(1))
        position = _strip_tags(cells[1])
        location = _strip_tags(cells[2])

        if len(cells) >= 6:
            salary = _strip_tags(cells[3]) or None
            posting_cell = cells[4]
        else:
            salary = None
            posting_cell = cells[3]

        link_match = _HREF_RE.search(posting_cell)
        link = link_match.group(1) if link_match else None
        if not company or not position or not link:
            continue

        rows.append({
            "company": company, "title": position, "location": location,
            "salary": salary, "link": link,
        })
    return rows


def _seen_key(link: str) -> str:
    row_hash = hashlib.sha1(link.encode("utf-8")).hexdigest()[:16]
    return f"icarus:job_scout:repo_seen:{row_hash}"


async def _is_seen(link: str) -> bool:
    from backend.database.redis_connection import get_redis_client
    redis = get_redis_client()
    return bool(await redis.exists(_seen_key(link)))


async def _mark_seen(link: str) -> None:
    from backend.database.redis_connection import get_redis_client
    redis = get_redis_client()
    await redis.set(_seen_key(link), "1", ex=SEEN_KEY_TTL)


async def fetch_new_postings() -> list[dict]:
    """Fetch the repo's README, parse all three sections, and return only
    rows not already dispatched (deduped against Redis by apply-link hash —
    same TTL-key shape as spam_sweep.py's _is_seen/_mark_seen, so state
    survives a container restart rather than living in an in-memory set)."""
    readme = await github_read_file(REPO_OWNER, REPO_NAME, README_PATH)
    if readme.startswith("Error"):
        logger.warning(f"[github_repo_producer] Failed to fetch README: {readme}")
        return []

    all_rows = []
    for _label, start_marker, end_marker in _SECTION_MARKERS:
        section = _extract_section(readme, start_marker, end_marker)
        if not section:
            logger.warning(
                f"[github_repo_producer] Section markers not found: "
                f"{start_marker}/{end_marker} — repo format may have changed."
            )
            continue
        all_rows.extend(_parse_table_rows(section))

    new_rows = []
    for row in all_rows:
        if await _is_seen(row["link"]):
            continue
        await _mark_seen(row["link"])
        new_rows.append(row)
    return new_rows


async def run_repo_producer():
    """Periodic loop — same asyncio while-True + try/except + sleep shape as
    spam_sweep.py / calendar_watcher.py. Wire into main.py's lifespan() the
    same way those two are."""
    from .orchestrator import dispatch_worker_task

    logger.info(
        f"[github_repo_producer] Watching {REPO_OWNER}/{REPO_NAME} "
        f"every {POLL_INTERVAL_SECONDS // 3600}h"
    )
    while True:
        try:
            new_rows = await fetch_new_postings()
            if new_rows:
                logger.info(f"[github_repo_producer] {len(new_rows)} new posting(s)")
            for row in new_rows:
                stub = {**row, "source": f"github_repo:{REPO_OWNER}/{REPO_NAME}"}
                await dispatch_worker_task("tasks:job_scout", {"stub": stub})
        except Exception as e:
            logger.error(f"[github_repo_producer] Poll error: {e}")
        await asyncio.sleep(POLL_INTERVAL_SECONDS)
